//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DE4Entities : DbContext
    {
        public DE4Entities()
            : base("name=DE4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LichSu> LichSus { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<TuyenTruyen> TuyenTruyens { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
