//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuyenTruyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TuyenTruyen()
        {
            this.LichSus = new HashSet<LichSu>();
        }
    
        public int ID { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public string TenDonVi { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> DaDuyet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSu> LichSus { get; set; }
    }
}
